config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  
  devise_for :users

  resources :users do
    resources :orders
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :authentication_keys => [:first_name, :given_name]
  has_many :orders
   # ログイン認証
  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    login = conditions.delete(:login)
    if login
      #where(conditions).where(["lower(email) = lower(:email) AND group_id = :group_id", { :email => email, :group_id => group_id }]).first
      where(conditions).where(["first_name = :first_name AND given_name = :given_name", { :first_name => first_name, :given_name => given_name }]).first
    else
      where(conditions).first
    end
  end

    # 登録時に email を不要にする
  def email_required?
    false
  end
  def email_changed?
    false
  end

  def will_save_change_to_email?
    false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  protected

  def devise_parameter_sanitizer
  	if resource_class == User
  		User::ParameterSanitizer.new(User, :user, params)
  	else
  		super # Use the default one
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def index
  end

  def new
    @order = Order.new
  end

  def create
    @order = Order.new(order_params)
    add_values(@order)
    #@order.work_place_range = params[:work_place_range]
    #@order.work_type = params[:work_type]
    #@order.car_type = params[:car_type]
    #@order.user_id = params[:user_id]
    #@order.loading_work = params[:loading_work]
      binding.pry
    if @order.save
    else
    end
  end

  def destroy
  end

  def edit
  end

  def update
  end

  private

    def order_params
      params.require(:order).permit(:work_place_range, :work_place ,:start_date,:finish_date, :work_type, :loading_work, :car_type, :attention)
    end

    def add_values(order)
      order.work_place_range = params[:work_place_range]
      order.work_type = params[:work_type]
      order.car_type = params[:car_type]
      order.loading_work = params[:loading_work]
      order.user_id = params[:user_id]
    end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>
<% if user_signed_in? %>
	<%= link_to 'ログアウト',destroy_user_session_path, method: :delete %>
	<%= link_to 'GO', new_user_order_path(current_user.id) ,method: :get %>
<% else %>
	<%= link_to 'サインイン', new_user_session_path, method: :get %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Akitakensetu</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/orders/create.html.erb
<h1>Orders#create</h1>
<p>Find me in app/views/orders/create.html.erb</p>

app/views/orders/destroy.html.erb
<h1>Orders#destroy</h1>
<p>Find me in app/views/orders/destroy.html.erb</p>

app/views/orders/edit.html.erb
<h1>Orders#edit</h1>
<p>Find me in app/views/orders/edit.html.erb</p>

app/views/orders/index.html.erb
<h1>Orders#index</h1>
<p>Find me in app/views/orders/index.html.erb</p>

app/views/orders/new.html.erb
<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">

<ul class="stepNav threeWide">
  <li><a href="" title="">検索</a></li>
    <li><a href="" title="">空車を確認</a></li>
    <li class="selected"><a href="" title="">予約する</a></li>
</ul>

<div class="container">
    <div class="col-md-2">
    </div>
    <div class="col-md-8">
    <div class="outer_box" >
	    <h2 style="text-align: center;,font-weight: 200;">
	    		ステップ 3/3
	    </h2>
		<hr>
		<%= form_for @order,url: user_orders_path(user_id: params[:user_id]) do |f|  %>
		<div class="simple_box" >
		  	<div class="radio-buttons">
		    	<table>
		    		<div><h4 class="btn-works">場所に該当する地区を選択してください</h4></div>
		      	<tr><%= f.label :場所の地区 %>
		      		<%= f.radio_button :work_place_range, {} %><br />
		        	<td>
			          	<input type="radio" name="work_place_range" id="place_1" value="名古屋市内" checked>
			          	<label class="button-style-label" for="place_1">名古屋市内</label>
		        	</td>
			        <td>
			          	<input type="radio" name="work_place_range" id="place_2" value="名古屋市外">
			          	<label class="button-style-label" for="place_2">名古屋市外</label>
			        </td>
			        <td>
			          	<input type="radio" name="work_place_range" id="place_3" value="愛知県内">
			          	<label class="button-style-label" for="place_3">愛知県内</label>
			        </td>
		        	<td>
			          	<input type="radio" name="work_place_range" id="place_4" value="東海地方">
			          	<label class="button-style-label" for="place_4">東海地方</label>
		        	</td>
			        <td>
			          	<input type="radio" name="work_place_range" id="place_5" value="それ以外">
			          	<label class="button-style-label" for="place_5">それ以外</label>
			        </td>
		      	</tr>
		    	</table>
		  	</div>
			<div>
				<div><h4 class="btn-works">場所の詳細を記入してください</h4></div>
				<%= f.label :場所詳細 %>
				<%= f.text_field :work_place, class:"form-control input-lg",placeholder: " 例) 愛知県名古屋市千種区〇〇町" %>
		  	</div>
		</div>
		<div class="simple_box" >
		<div class="radio-buttons">
		    <table>
		    	<div><h4 class="btn-works">日時を選択してください</h4></div>
		    	<%= f.label :日時 %>
		    	<div style="text-align: center;">
		    		<h4 class="btn-start">開始</h4>
		    	</div>
		      	<tr>
			      	<td>
			      		<div>
				      		<%= raw sprintf(
				              	f.date_select(
				                  :start_date,
				                  use_month_numbers: true,
				                  start_year:        Date.today.year,
				                  default:           Date.today,
				                  date_separator:    '%s'), # 年月日区切りをそれぞれ指定
				              '年 ', '月 ') + ' 日　'
				   			%>
			   			</div>
			      	</td>
			      	<%= f.radio_button :start_date_detail, {} %><br />
			        <td>
			          	<input type="radio" name="start_date_detail" id="am_1" value="午前１" checked>
			          	<label class="date-detail" for="am_1">午前①</label>
			        </td>
			        <td>
			          	<input type="radio" name="start_date_detail" id="am_2" value="午前２">
			          	<label class="date-detail" for="am_2">午前②</label>
			        </td>
		      	</tr>
		    </table>
	  	</div>

		<div class="radio-buttons">
		    <table>
		    	<div style="text-align: center;">
		    		<div><h4 class="btn-finish">終了</h4></div>
		    	</div>
		      	<tr>
			      	<td>
			      		<div>
				      		<%= raw sprintf(
				              f.date_select(
				                  :finish_date,
				                  use_month_numbers: true,
				                  start_year:        Date.today.year,
				                  default:           Date.today,
				                  date_separator:    '%s'),
				                   # 年月日区切りをそれぞれ指定
				              '年 ', '月 ') + ' 日　'
				   			%>
			   			</div>
			      	</td>
			      		<%= f.radio_button :finish_date_detail, {} %><br />
			        <td>
			          	<input type="radio" name="finish_date_detail" id="pm_1" value="午後１" checked>
			          	<label class="date-detail" for="pm_1">午後①</label>
			        </td>
			        <td>
			          	<input type="radio" name="finish_date_detail" id="pm_2" value="午後２">
			          	<label class="date-detail" for="pm_2">午後②</label>
			        </td>
		      	</tr>
		    </table>
	  	</div>
	  	</div>

	  	<div class="simple_box" >
	  	<div class="radio-buttons">
	    <table>
		      	<tr>
		    		<div><h4 class="btn-works">車種を選択してください</h4></div>
		      	<%= f.label :必要な車種はどちらになりますか？ %>
		      	<%= f.radio_button :car_type, {} %><br />
			        <td>
			          <input type="radio" name="car_type" id="car_1" value="4t車" checked>
			          <label class="button-style-label" for="car_1">4t車</label>
			        </td>
			        <td>
			          <input type="radio" name="car_type" id="car_2" value="ユニット車">
			          <label class="button-style-label" for="car_2">ユニット車</label>
			        </td>
			        <td>
			          <input type="radio" name="car_type" id="car_3" value="10t車">
			          <label class="button-style-label" for="car_3">10t車</label>
			        </td>
			        <td>
			          <input type="radio" name="car_type" id="car_4" value="2t車">
			          <label class="button-style-label" for="car_4">2t車</label>
			        </td>
		      	</tr>
		    </table>
	  	</div>

	    <div class="radio-buttons">
	    	<table>
	      		<tr>
		    		<div><h4 class="btn-works">内容を選択してください</h4></div>
	      		<%= f.label :今回はどのような件でしょうか？ %>
	      		<%= f.radio_button :work_type, {} %><br />
			        <td>
			          	<input type="radio" name="work_type" id="work_1" value="設置" checked>
			          	<label class="button-style-label" for="work_1">設置</label>
			        </td>
			        <td>
			         	<input type="radio" name="work_type" id="work_2" value="交換">
			          	<label class="button-style-label" for="work_2">交換</label>
			        </td>
			        <td>
			          	<input type="radio" name="work_type" id="work_3" value="引き上げ">
			          	<label class="button-style-label" for="work_3">引き上げ</label>
			        </td>
	      		</tr>
	    	</table>
	  	</div>

	    <div class="radio-buttons">
	    	<table>
		      	<tr>
		      	<div>
		      	<h4 class="btn-works">	積み込み作業の有無を選択してください
		      	</h4>
		    	</div>
		      	<%= f.label :積み込み作業はございますか？ %>
		      	<%= f.radio_button :loading_work, {} %><br />
			        <td>
			          	<input type="radio" name="loading_work" id="loading_1" value= true checked>
			          	<label class="button-style-label" for="loading_1">あり</label>
			        </td>
			        <td>
			          	<input type="radio" name="loading_work" id="loading_2" value= false>
			          	<label class="button-style-label" for="loading_2">なし</label>
			        </td>
		      	</tr>
	    	</table>
	  	</div>
	  		<div class="column">
			    <div class="input-text">
			    	<%= f.label :備考　%>
			  		<%= f.text_area :attention %>
				</div>
			</div>
	  	</div>

　　　　　<p style="color:red;,font-weight:200;,text-align: center">※下の「予約する」のボタンを押すと予約が確定します。</p>
		<%= f.submit '予約する', class: 'btn btn-primary btn-lg btn-block' %>
		<% end %>
	</div>
	</div>
</div>

app/views/orders/update.html.erb
<h1>Orders#update</h1>
<p>Find me in app/views/orders/update.html.erb</p>

app/views/search/index.html.erb
<h1>Search#index</h1>
<p>Find me in app/views/search/index.html.erb</p>

app/views/search/show.html.erb
<h1>Search#show</h1>
<p>Find me in app/views/search/show.html.erb</p>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>